name: Workflow for checking http status codes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://3.15.185.236:8080/random-number"]'
        expected: '[301, 200]'
    # ... uses ....
    
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://3.15.185.236:8080/get-random-number", "http://3.15.185.236:9090/metrics"]'
        expected: '[301, 200]'
    # ... uses ....
    
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://3.15.185.236:9090/metrics"]'
        expected: '[301, 200]'
    # ... uses ....
