name: Workflow for checking http status codes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://localhost:8080/random-number", "http://localhost:9090/metrics"]'
        expected: '[301, 200]'
    # ... uses ....
