name: Workflow for checking http status codes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... uses ....
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://3.15.185.236:9090/metrics", "https://github.com"]'
        expected: '[200, 200]'
    # ... uses ....
